Controllers/GradeController.cs
using AdmnPanel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AdmnPanel.Controllers
{
    public class GradeController : Controller
    {
       
        private IConfiguration configuration;

        public GradeController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult GradeList()
        {
            DataTable dataTable = new DataTable();
            string connectionString = configuration.GetConnectionString("ConnectionString");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_SelectAll_Grade", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            dataTable.Load(reader);
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Error fetching grade list.";
                    Console.WriteLine(ex.ToString());
                }
            }
            return View(dataTable);
        }

        public IActionResult GradeDelete(int GradeID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_Delete_Grade", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.Add("@GradeID", SqlDbType.Int).Value = GradeID;
                        command.ExecuteNonQuery();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("GradeList");
        }

        public IActionResult AddEditGrade(int GradeID)
        {
            string connectionString = configuration.GetConnectionString("ConnectionString");
            DataTable table = new DataTable();
            GradeModel gradeModel = new GradeModel();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_SelectByID_Grade", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@GradeID", GradeID);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            table.Load(reader);
                        }
                    }

                    foreach (DataRow dataRow in table.Rows)
                    {
                        gradeModel.GradeID = Convert.ToInt32(dataRow["GradeID"]);
                        gradeModel.GradeName = dataRow["Name"].ToString();
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Error fetching grade details.";
                    Console.WriteLine(ex.ToString());
                }
            }
            return View("AddEditGrade", gradeModel);
        }

        public IActionResult GradeSave(GradeModel gradeModel)
        {
            if (string.IsNullOrWhiteSpace(gradeModel.GradeName))
            {
                ModelState.AddModelError("Name", "Grade Name is required.");
            }

            if (ModelState.IsValid)
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandType = CommandType.StoredProcedure;

                        if (gradeModel.GradeID == 0)
                        {
                            command.CommandText = "PR_Insert_Grade";
                        }
                        else
                        {
                            command.CommandText = "PR_Update_Grade";
                            command.Parameters.Add("@GradeID", SqlDbType.Int).Value = gradeModel.GradeID;
                        }

                        command.Parameters.Add("@Name", SqlDbType.NVarChar, 255).Value = gradeModel.GradeName;

                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("GradeList");
            }

            return View("AddEditGrade", gradeModel);
        }

    }
}

Controllers/HomeController.cs
using AdmnPanel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdmnPanel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult TableList()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SkillController.cs
using AdmnPanel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;

namespace AdmnPanel.Controllers
{
    public class SkillController : Controller
    {
        private IConfiguration configuration;

        public SkillController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult SkillList()
        {
            DataTable dataTable = new DataTable();
            string connectionString = configuration.GetConnectionString("ConnectionString");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_SelectAll_Skill", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            dataTable.Load(reader);
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Error fetching skill list.";
                    Console.WriteLine(ex.ToString());
                }
            }
            return View(dataTable);
        }

        public IActionResult SkillDelete(int SkillID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_Delete_Skill", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.Add("@SkillID", SqlDbType.Int).Value = SkillID;
                        command.ExecuteNonQuery();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("SkillList");
        }

        public IActionResult AddEditSkill(int SkillID)
        {
            

            string connectionString = configuration.GetConnectionString("ConnectionString");
            DataTable table = new DataTable();
            SkillModel model = new SkillModel();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_SelectByID_Skill", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@SkillID", SkillID);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            table.Load(reader);
                        }
                    }

                    foreach (DataRow dataRow in table.Rows)
                    {
                        model.SkillID = Convert.ToInt32(dataRow["SkillID"]);
                        model.SkillName = dataRow["SkillName"].ToString();
                        model.Sequence = Convert.ToInt32(dataRow["Sequence"]);
                        model.ShortDescription = dataRow["ShortDescription"].ToString();
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Error fetching skill details.";
                    Console.WriteLine(ex.ToString());
                }
            }
            return View("AddEditSkill", model);
        }

        public IActionResult SkillSave(SkillModel model)
        {
            if (string.IsNullOrWhiteSpace(model.SkillName))
            {
                ModelState.AddModelError("SkillName", "Skill Name is required.");
            }

            if (ModelState.IsValid)
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandType = CommandType.StoredProcedure;

                        if (model.SkillID == 0)
                        {
                            command.CommandText = "PR_Insert_Skill";
                        }
                        else
                        {
                            command.CommandText = "PR_Update_Skill";
                            command.Parameters.Add("@SkillID", SqlDbType.Int).Value = model.SkillID;
                        }

                        command.Parameters.Add("@SkillName", SqlDbType.NVarChar, 255).Value = model.SkillName;
                        command.Parameters.Add("@Sequence", SqlDbType.Int).Value = model.Sequence;
                        command.Parameters.Add("@ShortDescription", SqlDbType.NVarChar, -1).Value = model.ShortDescription;

                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("SkillList");
            }
            return View("AddEditSkill", model);
        }


       
    }
}

Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using AdmnPanel.Models;

namespace AdmnPanel.Controllers
{
    public class SubjectController : Controller
    {
        private IConfiguration configuration;

        public SubjectController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult SubjectList()
        {
            DataTable dataTable = new DataTable();
            string connectionString = configuration.GetConnectionString("ConnectionString");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_SelectAll_Subject", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            dataTable.Load(reader);
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Error fetching subject list.";
                    Console.WriteLine(ex.ToString());
                }
            }
            return View(dataTable);
        }

        public IActionResult SubjectDelete(int SubjectID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_Delete_Subject", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.Add("@SubjectID", SqlDbType.Int).Value = SubjectID;
                        command.ExecuteNonQuery();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("SubjectList");
        }

        public IActionResult AddEditSubject(int SubjectID)
        {
            string connectionString = configuration.GetConnectionString("ConnectionString");
            DataTable table = new DataTable();
            SubjectModel subjectModel = new SubjectModel();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                try
                {
                    connection.Open();
                    using (SqlCommand command = new SqlCommand("PR_SelectByID_Subject", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@SubjectID", SubjectID);
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            table.Load(reader);
                        }
                    }

                    foreach (DataRow dataRow in table.Rows)
                    {
                        subjectModel.SubjectID = Convert.ToInt32(dataRow["SubjectID"]);
                        subjectModel.SubjectName = dataRow["Name"].ToString();
                    }
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Error fetching subject details.";
                    Console.WriteLine(ex.ToString());
                }
            }
            return View("AddEditSubject", subjectModel);
        }

        public IActionResult SubjectSave(SubjectModel subjectModel)
        {
            if (string.IsNullOrWhiteSpace(subjectModel.SubjectName))
            {
                ModelState.AddModelError("Name", "Subject Name is required.");
            }

            if (ModelState.IsValid)
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandType = CommandType.StoredProcedure;

                        if (subjectModel.SubjectID == 0)
                        {
                            command.CommandText = "PR_Insert_Subject";
                        }
                        else
                        {
                            command.CommandText = "PR_Update_Subject";
                            command.Parameters.Add("@SubjectID", SqlDbType.Int).Value = subjectModel.SubjectID;
                        }

                        command.Parameters.Add("@Name", SqlDbType.NVarChar, 255).Value = subjectModel.SubjectName;

                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("SubjectList");
            }

            return View("AddEditSubject", subjectModel);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home - Kids Learning";
}

<div class="text-center">
    <h1 class="display-3 text-primary fw-bold">🎉 Welcome to Kids Learning! 🎨📚</h1>
    <p class="lead text-secondary">Fun and interactive lessons for young learners!</p>

    

    <p class="mt-4">Ready to start learning? 🚀</p>
    <a asp-action="TableList" asp-controller="Home"  class="btn btn-primary btn-lg">Get Started</a>
</div>

<style>
    body {
        margin-top: 200px;
        background-color: #f9f9f9;
    }

    .card {
        transition: transform 0.3s ease-in-out;
    }

        .card:hover {
            transform: scale(1.05);
        }
</style>

Views/Home/TableList.cshtml
@{
    ViewData["Title"] = "Database Tables";
}

<style>
    body {
        margin-top: 200px;
        background: linear-gradient(to right, #ffefba, #ffffff); /* Soft Gradient */
        background: url('/images/math-bg.png') ;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }

    .card {
        border: none;
        transition: transform 0.3s ease-in-out;
    }

    .card:hover {
        transform: scale(1.05);
    }

    .card-body {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .card-title {
        font-size: 1.2rem;
        font-weight: bold;
    }

    .icon {
        font-size: 40px;
        margin-bottom: 10px;
        color: #007bff;
    }

    .highlight-heading {
        font-size: 2rem;
        font-weight: bold;
        color: #fff;
        background: linear-gradient(45deg, #007bff, #00c6ff);
        padding: 10px 20px;
        border-radius: 8px;
        display: inline-block;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
        margin-left: 500px;
    }

</style>

<h2 class="text-center highlight-heading">Database Tables</h2>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-4 mb-3">
            <a asp-controller="Grade" asp-action="GradeList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-graduation-cap"></i>
                        <h5 class="card-title">Grade</h5>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 mb-3">
            <a asp-controller="Subject" asp-action="SubjectList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-book"></i>
                        <h5 class="card-title">Subject</h5>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 mb-3">
            <a asp-controller="GradeWiseSubject" asp-action="GradewiseSubjectList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-layer-group"></i>
                        <h5 class="card-title">Gradewise Subject</h5>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 mb-3">
            <a asp-controller="Chapter" asp-action="ChapterList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-scroll"></i>
                        <h5 class="card-title">Chapter</h5>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 mb-3">
            <a asp-controller="Skill" asp-action="SkillList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-lightbulb"></i>
                        <h5 class="card-title">Skill</h5>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 mb-3">
            <a asp-controller="GradewiseChapter" asp-action="GradewiseChapterList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-file-alt"></i>
                        <h5 class="card-title">Gradewise Chapter</h5>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-3">
            <a asp-controller="GradewiseSkill" asp-action="GradewiseSkillList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-file-alt"></i>
                        <h5 class="card-title">Gradewise Skill</h5>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-3">
            <a asp-controller="SkillRoutes" asp-action="SkillRoutesList" class="text-decoration-none">
                <div class="card shadow-sm">
                    <div class="card-body text-center">
                        <i class="icon fas fa-file-alt"></i>
                        <h5 class="card-title">SkillRoutes Skill</h5>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

<!-- FontAwesome for Icons -->
<script src="https://kit.fontawesome.com/YOUR-KIT-ID.js" crossorigin="anonymous"></script>